version: '3.8'
services:
  db:
    container_name: shaberu_db
    image: postgres:latest
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    ports:
    - "5432:5432"
    volumes:
    - shaberu_db:/var/lib/postgresql/data
  app:
    container_name: shaberu_app
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - db_network
      - web_network
    depends_on:
      - db
  nginx:
    container_name: shaberu_webserver
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - appseed-app
volumes:
  shaberu_db:
    driver: local
networks:
  shaberu_db_network:
    driver: bridge
  shaberu_web_network:
    driver: bridge
 