version: '3.8'
services:
  db:
    container_name: shaberu_db
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - shaberu_db_network
    volumes:
      - shaberu_db:/var/lib/postgresql/data
  app:
    container_name: shaberu_app
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile-dev
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - shaberu_db_network
      - shaberu_web_network
    volumes:
      - shaberu_app:/var/shaberu
      - shaberu_site:/usr/local/lib/python3.11/site-packages/
    depends_on:
      - db
  nginx:
    container_name: shaberu_webserver
    image: "nginx:latest"
    restart: always
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - shaberu_web_network
    depends_on: 
      - app
volumes:
  shaberu_db:
    driver: local
  shaberu_app:
    driver: local
  shaberu_site:
    driver: local
networks:
  shaberu_db_network:
    driver: bridge
  shaberu_web_network:
    driver: bridge
 