# Generated by Django 4.2.7 on 2023-11-29 19:50

from django.db import migrations, models
import language.validators


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0005_alter_languagemodel_cr_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagemodel',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Is default'),
        ),
        migrations.AlterField(
            model_name='languagemodel',
            name='file',
            field=models.CharField(blank=True, default='', max_length=255, validators=[language.validators.validate_path], verbose_name='Model path'),
        ),
        migrations.AddConstraint(
            model_name='languagemodel',
            constraint=models.UniqueConstraint(fields=('name', 'type', 'is_default'), name='Unique default model'),
        ),
    ]
