# Generated by Django 4.2.7 on 2023-11-28 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTextMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_date', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('text', models.TextField(blank=True, default='', verbose_name='Message')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User text message',
                'verbose_name_plural': 'User text messages',
                'indexes': [models.Index(fields=['user'], name='history_use_user_id_60f6ad_idx'), models.Index(fields=['text'], name='history_use_text_4271d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAudioMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_date', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('path', models.FileField(default='', upload_to='system/audio-msgs/', verbose_name='Model path')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User audio message',
                'verbose_name_plural': 'User audio messages',
                'indexes': [models.Index(fields=['user'], name='history_use_user_id_8902dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='BotTextMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_date', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('text', models.TextField(blank=True, default='', verbose_name='Message')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_language_model', to='language.languagemodel', verbose_name='Language model')),
            ],
            options={
                'verbose_name': 'Bot text message',
                'verbose_name_plural': 'Bot text messages',
                'indexes': [models.Index(fields=['model'], name='history_bot_model_i_ee9a4d_idx'), models.Index(fields=['text'], name='history_bot_text_68239e_idx')],
            },
        ),
        migrations.CreateModel(
            name='BotAudioMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_date', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('path', models.FileField(default='', upload_to='system/audio-msgs/', verbose_name='Model path')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_language_model', to='language.languagemodel', verbose_name='Language model')),
            ],
            options={
                'verbose_name': 'Bot audio message',
                'verbose_name_plural': 'Bot audio messages',
                'indexes': [models.Index(fields=['model'], name='history_bot_model_i_f45388_idx')],
            },
        ),
    ]
